[build.environment]
  NODE_VERSION = "24"
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"

[build]
  publish = "docs/.vitepress/dist"
  # pnpm docs:build = 构建 VitePress 源码 (pnpm build) + 构建文档站点
  command = "pnpm docs:build"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable'''
